import type { BoardColumn, BoardProject } from './types'

export const sampleColumns: BoardColumn[] = [
  { id: 'active', title: 'Active', order: 0 },
  { id: 'on-hold', title: 'On Hold', order: 1 },
  { id: 'completed', title: 'Completed', order: 2 },
  { id: 'archived', title: 'Archived', order: 3 },
]

export const sampleProjects: BoardProject[] = [
  {
    id: 'proj-001',
    name: 'project-watch',
    description: 'Local development project tracker with git and GitHub integration',
    localPath: '/Users/jmcconocha/Projects/project-watch',
    githubUrl: 'https://github.com/alexdev/project-watch',
    status: 'active',
    tags: ['typescript', 'electron', 'personal'],
    lastActivity: '2024-03-15T14:32:00Z',
    git: {
      branch: 'feature/kanban-board',
      isDirty: true,
      uncommittedFiles: 3,
      commitsAhead: 2,
      commitsBehind: 0,
    },
    github: {
      openPRs: 1,
      openIssues: 5,
    },
  },
  {
    id: 'proj-002',
    name: 'acme-dashboard',
    description: 'Analytics dashboard for Acme Corp client project',
    localPath: '/Users/jmcconocha/Projects/Work/clients/acme-dashboard',
    githubUrl: 'https://github.com/acme-corp/dashboard',
    status: 'active',
    tags: ['react', 'client', 'priority'],
    lastActivity: '2024-03-15T11:20:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 3,
    },
    github: {
      openPRs: 2,
      openIssues: 12,
    },
  },
  {
    id: 'proj-003',
    name: 'dotfiles',
    description: 'Personal shell configuration and dotfiles',
    localPath: '/Users/jmcconocha/Projects/dotfiles',
    githubUrl: 'https://github.com/alexdev/dotfiles',
    status: 'active',
    tags: ['config', 'personal'],
    lastActivity: '2024-03-14T09:15:00Z',
    git: {
      branch: 'main',
      isDirty: true,
      uncommittedFiles: 1,
      commitsAhead: 1,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 0,
    },
  },
  {
    id: 'proj-004',
    name: 'recipe-app',
    description: 'Mobile-first recipe collection and meal planning app',
    localPath: '/Users/jmcconocha/Projects/recipe-app',
    githubUrl: 'https://github.com/alexdev/recipe-app',
    status: 'active',
    tags: ['react-native', 'personal', 'mobile'],
    lastActivity: '2024-03-13T16:45:00Z',
    git: {
      branch: 'develop',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 3,
    },
  },
  {
    id: 'proj-005',
    name: 'blog-redesign',
    description: 'Redesigning personal blog with new CMS',
    localPath: '/Users/jmcconocha/Projects/blog-redesign',
    githubUrl: 'https://github.com/alexdev/blog-redesign',
    status: 'on-hold',
    tags: ['nextjs', 'personal'],
    lastActivity: '2024-02-28T10:00:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 2,
    },
  },
  {
    id: 'proj-006',
    name: 'invoice-tool',
    description: 'Simple invoicing tool for freelance work',
    localPath: '/Users/jmcconocha/Projects/invoice-tool',
    githubUrl: null,
    status: 'on-hold',
    tags: ['python', 'personal', 'cli'],
    lastActivity: '2024-02-15T14:30:00Z',
    git: {
      branch: 'main',
      isDirty: true,
      uncommittedFiles: 2,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 0,
    },
  },
  {
    id: 'proj-007',
    name: 'widget-corp-api',
    description: 'REST API for Widget Corp e-commerce platform',
    localPath: '/Users/jmcconocha/Projects/Work/clients/widget-corp-api',
    githubUrl: 'https://github.com/widget-corp/api',
    status: 'completed',
    tags: ['node', 'client', 'api'],
    lastActivity: '2024-03-01T17:00:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 0,
    },
  },
  {
    id: 'proj-008',
    name: 'portfolio-v2',
    description: 'Second version of personal portfolio website',
    localPath: '/Users/jmcconocha/Projects/portfolio-v2',
    githubUrl: 'https://github.com/alexdev/portfolio-v2',
    status: 'completed',
    tags: ['astro', 'personal'],
    lastActivity: '2024-01-20T12:00:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 1,
    },
  },
  {
    id: 'proj-009',
    name: 'old-blog',
    description: 'Original Jekyll-based blog (migrated to new platform)',
    localPath: '/Users/jmcconocha/Projects/old-blog',
    githubUrl: 'https://github.com/alexdev/old-blog',
    status: 'archived',
    tags: ['jekyll', 'personal', 'legacy'],
    lastActivity: '2023-06-15T09:00:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 0,
    },
  },
  {
    id: 'proj-010',
    name: 'experiments',
    description: 'Random code experiments and learning projects',
    localPath: '/Users/jmcconocha/Projects/experiments',
    githubUrl: null,
    status: 'archived',
    tags: ['learning'],
    lastActivity: '2023-04-01T15:30:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      uncommittedFiles: 0,
      commitsAhead: 0,
      commitsBehind: 0,
    },
    github: {
      openPRs: 0,
      openIssues: 0,
    },
  },
]
