import type { Project } from './types'

export const sampleProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'project-watch',
    description: 'A local development project tracker that monitors folders and GitHub repos',
    localPath: '/Users/jmcconocha/Projects/project-watch',
    githubUrl: 'https://github.com/alexdev/project-watch',
    priority: 'high',
    status: 'active',
    dueDate: '2024-02-28',
    progress: 65,
    lastActivity: '2024-02-10T14:32:00Z',
    git: {
      branch: 'feature/dashboard-filters',
      isDirty: true,
      commitsAhead: 3,
      commitsBehind: 0,
      openPRs: 1,
    },
  },
  {
    id: 'proj-002',
    name: 'recipe-app',
    description: 'Mobile-first recipe management app with meal planning features',
    localPath: '/Users/jmcconocha/Projects/recipe-app',
    githubUrl: 'https://github.com/alexdev/recipe-app',
    priority: 'medium',
    status: 'active',
    dueDate: '2024-03-15',
    progress: 40,
    lastActivity: '2024-02-09T09:15:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      commitsAhead: 0,
      commitsBehind: 2,
      openPRs: 0,
    },
  },
  {
    id: 'proj-003',
    name: 'dotfiles',
    description: 'Personal dotfiles and system configuration',
    localPath: '/Users/jmcconocha/Projects/dotfiles',
    githubUrl: 'https://github.com/alexdev/dotfiles',
    priority: 'low',
    status: 'active',
    dueDate: null,
    progress: 100,
    lastActivity: '2024-01-20T11:00:00Z',
    git: {
      branch: 'main',
      isDirty: true,
      commitsAhead: 5,
      commitsBehind: 0,
      openPRs: 0,
    },
  },
  {
    id: 'proj-004',
    name: 'client-portal',
    description: 'Client-facing dashboard for project updates and invoice management',
    localPath: '/Users/jmcconocha/Projects/client-portal',
    githubUrl: 'https://github.com/alexdev/client-portal',
    priority: 'high',
    status: 'active',
    dueDate: '2024-02-14',
    progress: 85,
    lastActivity: '2024-02-10T16:45:00Z',
    git: {
      branch: 'hotfix/auth-bug',
      isDirty: false,
      commitsAhead: 1,
      commitsBehind: 0,
      openPRs: 2,
    },
  },
  {
    id: 'proj-005',
    name: 'design-system',
    description: 'Shared component library and design tokens for all projects',
    localPath: '/Users/jmcconocha/Projects/design-system',
    githubUrl: 'https://github.com/alexdev/design-system',
    priority: 'medium',
    status: 'on-hold',
    dueDate: '2024-04-01',
    progress: 30,
    lastActivity: '2024-01-05T10:20:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      commitsAhead: 0,
      commitsBehind: 8,
      openPRs: 0,
    },
  },
  {
    id: 'proj-006',
    name: 'blog-platform',
    description: 'Markdown-based blogging platform with RSS and newsletter integration',
    localPath: '/Users/jmcconocha/Projects/blog-platform',
    githubUrl: 'https://github.com/alexdev/blog-platform',
    priority: 'none',
    status: 'archived',
    dueDate: null,
    progress: 100,
    lastActivity: '2023-11-15T08:00:00Z',
    git: {
      branch: 'main',
      isDirty: false,
      commitsAhead: 0,
      commitsBehind: 0,
      openPRs: 0,
    },
  },
  {
    id: 'proj-007',
    name: 'api-gateway',
    description: 'Central API gateway handling authentication, rate limiting, and request routing',
    localPath: '/Users/jmcconocha/Projects/api-gateway',
    githubUrl: 'https://github.com/alexdev/api-gateway',
    priority: 'high',
    status: 'active',
    dueDate: '2024-02-20',
    progress: 50,
    lastActivity: '2024-02-08T13:22:00Z',
    git: {
      branch: 'feature/rate-limiting',
      isDirty: true,
      commitsAhead: 7,
      commitsBehind: 1,
      openPRs: 3,
    },
  },
  {
    id: 'proj-008',
    name: 'mobile-app',
    description: 'React Native companion app for the client portal',
    localPath: '/Users/jmcconocha/Projects/mobile-app',
    githubUrl: null,
    priority: 'medium',
    status: 'active',
    dueDate: '2024-05-01',
    progress: 15,
    lastActivity: '2024-02-07T17:30:00Z',
    git: {
      branch: 'develop',
      isDirty: false,
      commitsAhead: 0,
      commitsBehind: 0,
      openPRs: 0,
    },
  },
]
